"""Public, versioned metadata used by the WorldEval Lab product surface.

The Lab registry deliberately describes existing environment capabilities without creating a new
authority or provider boundary.  Product/API layers can consume its canonical public projection
when they are ready to expose a catalogue or individual game guide pages.
"""

from .contracts import (
    RACE_CARTRIDGE_SCHEMA_VERSION,
    REPLAY_PROJECTION_SCHEMA_VERSION,
    RUN_CONTRACT_SCHEMA_VERSION,
    RUN_STATE_SCHEMA_VERSION,
    LabContractError,
    RaceCartridge,
    ReplayProjection,
    RunContract,
    RunEntrant,
    RunLifecycle,
    RunMode,
    RunState,
    assert_public_projection_safe,
)
from .games import (
    GAME_CATALOG,
    GAME_CATALOG_SCHEMA_VERSION,
    GAME_CATEGORIES,
    GAME_SPEC_SCHEMA_VERSION,
    GameAgentInterface,
    GameCapabilities,
    GameCatalog,
    GameCatalogError,
    GameCategory,
    GameCategoryId,
    GameConfigurationControl,
    GameInteractionKind,
    GameMetric,
    GameMode,
    GameParticipantRange,
    GameSafety,
    GameScoring,
    GameSpec,
    game_spec,
)
from .sandbox import (
    OPERATOR_ACTION_COURSE_SANDBOX_RECIPE,
    SANDBOX_MANIFEST_SCHEMA_VERSION,
    SANDBOX_PRIMITIVE_SCHEMA_VERSION,
    SANDBOX_PRIMITIVES,
    SANDBOX_RECIPE_SCHEMA_VERSION,
    SandboxAuthorityBinding,
    SandboxManifestError,
    SandboxPrimitiveSpec,
    SandboxRecipeLifecycle,
    SandboxRecipeSpec,
    draft_sandbox_recipe,
    resolve_sandbox_primitive_order,
    sandbox_manifest,
)

__all__ = [
    "GAME_CATALOG",
    "GAME_CATALOG_SCHEMA_VERSION",
    "GAME_CATEGORIES",
    "GAME_SPEC_SCHEMA_VERSION",
    "GameAgentInterface",
    "GameCapabilities",
    "GameCatalog",
    "GameCatalogError",
    "GameCategory",
    "GameCategoryId",
    "GameConfigurationControl",
    "GameInteractionKind",
    "GameMetric",
    "GameMode",
    "GameParticipantRange",
    "GameSafety",
    "GameScoring",
    "GameSpec",
    "LabContractError",
    "OPERATOR_ACTION_COURSE_SANDBOX_RECIPE",
    "RACE_CARTRIDGE_SCHEMA_VERSION",
    "REPLAY_PROJECTION_SCHEMA_VERSION",
    "RUN_CONTRACT_SCHEMA_VERSION",
    "RUN_STATE_SCHEMA_VERSION",
    "RaceCartridge",
    "ReplayProjection",
    "RunContract",
    "RunEntrant",
    "RunLifecycle",
    "RunMode",
    "RunState",
    "SANDBOX_MANIFEST_SCHEMA_VERSION",
    "SANDBOX_PRIMITIVES",
    "SANDBOX_PRIMITIVE_SCHEMA_VERSION",
    "SANDBOX_RECIPE_SCHEMA_VERSION",
    "SandboxAuthorityBinding",
    "SandboxManifestError",
    "SandboxPrimitiveSpec",
    "SandboxRecipeLifecycle",
    "SandboxRecipeSpec",
    "assert_public_projection_safe",
    "draft_sandbox_recipe",
    "game_spec",
    "resolve_sandbox_primitive_order",
    "sandbox_manifest",
]
